PLANT_DISEASES = {
    0: {"name": "Apple Scab", "plant": "Apple", "severity": "High",
        "treatment": "Apply fungicide every 7-10 days. Remove infected leaves immediately."},
    1: {"name": "Apple Black Rot", "plant": "Apple", "severity": "High",
        "treatment": "Prune infected branches. Apply copper-based fungicide."},
    2: {"name": "Cedar Apple Rust", "plant": "Apple", "severity": "Medium",
        "treatment": "Apply myclobutanil fungicide. Remove nearby cedar trees."},
    3: {"name": "Healthy", "plant": "Apple", "severity": "None",
        "treatment": "Your apple plant looks healthy! Keep up good care."},
    4: {"name": "Powdery Mildew", "plant": "Cherry", "severity": "Medium",
        "treatment": "Apply sulfur-based fungicide. Improve air circulation."},
    5: {"name": "Healthy", "plant": "Cherry", "severity": "None",
        "treatment": "Your cherry plant looks healthy!"},
    6: {"name": "Gray Leaf Spot", "plant": "Corn", "severity": "High",
        "treatment": "Use resistant varieties. Apply fungicide at early stages."},
    7: {"name": "Common Rust", "plant": "Corn", "severity": "Medium",
        "treatment": "Apply fungicide early. Plant resistant corn varieties."},
    8: {"name": "Northern Leaf Blight", "plant": "Corn", "severity": "High",
        "treatment": "Apply fungicide. Use disease-resistant seed varieties."},
    9: {"name": "Healthy", "plant": "Corn", "severity": "None",
        "treatment": "Your corn plant looks healthy!"},
    10: {"name": "Black Rot", "plant": "Grape", "severity": "High",
         "treatment": "Remove mummified fruits. Apply fungicide in spring."},
    11: {"name": "Esca Disease", "plant": "Grape", "severity": "Very High",
         "treatment": "No cure available. Remove infected plants to stop spread."},
    12: {"name": "Leaf Blight", "plant": "Grape", "severity": "Medium",
         "treatment": "Apply copper fungicide. Remove infected leaves."},
    13: {"name": "Healthy", "plant": "Grape", "severity": "None",
         "treatment": "Your grape plant looks healthy!"},
    14: {"name": "Citrus Greening", "plant": "Orange", "severity": "Very High",
         "treatment": "No cure. Remove infected trees. Control psyllid insects."},
    15: {"name": "Bacterial Spot", "plant": "Peach", "severity": "High",
         "treatment": "Apply copper fungicide. Avoid overhead irrigation."},
    16: {"name": "Healthy", "plant": "Peach", "severity": "None",
         "treatment": "Your peach plant looks healthy!"},
    17: {"name": "Bacterial Spot", "plant": "Pepper", "severity": "Medium",
         "treatment": "Apply copper-based bactericide. Remove infected plants."},
    18: {"name": "Healthy", "plant": "Pepper", "severity": "None",
         "treatment": "Your pepper plant looks healthy!"},
    19: {"name": "Early Blight", "plant": "Potato", "severity": "Medium",
         "treatment": "Apply chlorothalonil fungicide. Remove infected leaves."},
    20: {"name": "Late Blight", "plant": "Potato", "severity": "Very High",
         "treatment": "Apply fungicide immediately. This destroyed Ireland in 1845!"},
    21: {"name": "Healthy", "plant": "Potato", "severity": "None",
         "treatment": "Your potato plant looks healthy!"},
    22: {"name": "Squash Powdery Mildew", "plant": "Squash", "severity": "Medium",
         "treatment": "Apply neem oil or sulfur fungicide. Improve air circulation."},
    23: {"name": "Leaf Scorch", "plant": "Strawberry", "severity": "Medium",
         "treatment": "Apply fungicide. Remove infected leaves. Avoid wet foliage."},
    24: {"name": "Healthy", "plant": "Strawberry", "severity": "None",
         "treatment": "Your strawberry plant looks healthy!"},
    25: {"name": "Bacterial Spot", "plant": "Tomato", "severity": "High",
         "treatment": "Apply copper bactericide. Use disease-free seeds."},
    26: {"name": "Early Blight", "plant": "Tomato", "severity": "Medium",
         "treatment": "Apply fungicide. Remove lower infected leaves."},
    27: {"name": "Late Blight", "plant": "Tomato", "severity": "Very High",
         "treatment": "Apply fungicide immediately. Remove infected plants."},
    28: {"name": "Leaf Mold", "plant": "Tomato", "severity": "Medium",
         "treatment": "Improve ventilation. Apply fungicide. Reduce humidity."},
    29: {"name": "Septoria Leaf Spot", "plant": "Tomato", "severity": "Medium",
         "treatment": "Apply fungicide. Remove infected leaves from base up."},
    30: {"name": "Spider Mites", "plant": "Tomato", "severity": "Medium",
         "treatment": "Apply miticide or neem oil. Increase humidity around plants."},
    31: {"name": "Target Spot", "plant": "Tomato", "severity": "Medium",
         "treatment": "Apply fungicide. Remove crop debris after harvest."},
    32: {"name": "Yellow Leaf Curl Virus", "plant": "Tomato", "severity": "Very High",
         "treatment": "No cure. Remove infected plants. Control whitefly insects."},
    33: {"name": "Mosaic Virus", "plant": "Tomato", "severity": "High",
         "treatment": "No cure. Remove infected plants. Wash hands after handling."},
    34: {"name": "Healthy", "plant": "Tomato", "severity": "None",
         "treatment": "Your tomato plant looks healthy! Keep up the good work."},
}

SEVERITY_COLORS = {
    "None": "green",
    "Medium": "orange",
    "High": "red",
    "Very High": "darkred"
}